### ISSUE TITLE
Problem with iqtree2

### ISSUE THREAD

**Issue by genomesandMGEs** [gem-pasteur/PanACoTA#13]
Hi,

I tried to build a tree of my alignment created using the `align` subcommand, using the default iqtree2. However, I got this error message: 

`* [2021-03-29 11:25:44] : ERROR  error: command '>iqtree2 -s Phylo-ACBA2009/ACBA2009.grp.aln -T 32 -m GTR    --seqtype DNA --prefix IQtree2/ACBA2009.grp.aln.iqtree_tree --quiet ' is not possible.`

Using the `-s iqtree` option, I managed to run the `tree` subcommand. I installed panacota using anaconda; I went to anaconda/envs/panacota/bin and only found the command `iqtree` (version 2.0.3). Maybe creating a new command named `iqtree2` and store it in the same path will solve the issue?

Thank you!

**Comment by asetGem** [comment]
Hi,
Can you tell me which version of panacota you installed please, and the command line you used?
Thanks

**Comment by genomesandMGEs** [comment]
Sure. I have installed `v. 1.2.0` and used `PanACoTA tree -a Phylo-2009/2009.grp.aln -o IQtree2 --threads 32`

**Comment by asetGem** [comment]
Creating the new command named iqtree2 should solve the error, yes, but it is supposed to already work by using 'iqtree'.

Can you tell me what is your output if you run (in the same environment as where you are running panacota):

`iqtree2 -s Phylo-ACBA2009/ACBA2009.grp.aln -T 32 -m GTR --seqtype DNA --prefix IQtree2/ACBA2009.grp.aln.iqtree_tree --quiet` 
and
`iqtree -s Phylo-ACBA2009/ACBA2009.grp.aln -T 32 -m GTR --seqtype DNA --prefix IQtree2/ACBA2009.grp.aln.iqtree_tree --quiet`

**Comment by genomesandMGEs** [comment]
for the `iqtree2` command I got the command not found error; for the `iqtree` I got `ERROR: Could not open IQtree2/ACBA2009.grp.aln.iqtree_tree.log` for logging

**Comment by asetGem** [comment]
I cannot manage to reproduce this behaviour. I installed IQtree v 2.0.5, which is run with the command 'iqtree'. iqtree2 does not exist, like you. When I run the tree module, it is using iqtree as expected.

Do you have a possibility to install PanACoTA from the github repository? You can install with `./make develop`, so that you will just have to remove a repository after. Then, try to run the same command. This will allow to do some tests, which we cannot do with a fix version of conda.

**Comment by asetGem** [comment]
Can you tell me if you still have the error with the new 1.3.0 version?
