### ISSUE TITLE
the error about "The core genome contains 0 families"

### ISSUE THREAD

**Issue by albertzhuo** [gem-pasteur/PanACoTA#15]
When I tried to use PanACoTA software to analyze Haemophilus influenzae (TAXID=727), I got an exception in the "align" step and traced it back to the error in the corepers step. Although it did not appear as an error, it reported this sentence "The core genome contains 0 families, each one having exactly 207 members, from the 207 different genomes."
I would like to understand the meaning of this sentence, why it appears, and how to solve the problem behind this sentence and continue with the "align" step.

**Comment by albertzhuo** [comment]
[Uploading logfile.tar.zip…]()

**Comment by asetGem** [comment]
Hello,
This message means that the core genome of your dataset is empty. I cannot download your logfile, but as far as I can see from your post, you have 207 genomes in your dataset. A family is in the core genome if it contains 207 genes, with 1 from each of your 207 genomes. Apparently, this never happens in your dataset. 

This can be due to several reasons. Among them, important parameters are the kind of data you are using (draft and/or complete genomes), and if you annotated all genomes with a same pipeline (using `PanACoTA annotate` or any other software). 

So, the first thing you could try (if not already done) is to use a same software to re-annotate your genomes (syntactic annotations are enough, no need for functional annotation), and to eliminate too bad quality genomes: this can be done by the `PanACoTA annotate` module. However, even with this done, as you have more than 200 genomes (and I guess many are drafts), it is not uncommon to get an empty core genome.

So, you could try using the persistent genome instead of the core genome (allowing families where gene(s) from some genomes are absent). For example, for a persistent genome at 99% (genes can be missing in 1% of your genomes, meaning at most 2 genomes in your case): `PanACoTA corepers -p <pangenome_file> -t 0.99 `. According to the downstream analysis you want to do after, you can adapt the threshold, and/or adopt a more relaxed definition, by using the mixed (`-X`) or multi (`-M`) persistent genome (see https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/usage.html#do-corepers for more info, or fig.3 of the paper https://academic.oup.com/nargab/article/3/1/lqaa106/6090162).

I hope this will help you. Do not hesitate to ask me if something is unclear!

**Comment by albertzhuo** [comment]
well ,a bad news is after I executed the command with "-X"and"-t 0.99" OR "-X" and "-t 0.99"
in the align step it still report error.....that's heart broken...
HELP ME!THANKS!
the error log will share by google drive
[https://drive.google.com/file/d/17N0YLe1VUDSOzUxGtlNYArnyLZ-XTYxi/view?usp=sharing
](url)
thanks！！！！！！！！！

**Comment by knishiura3** [comment]
I've encountered the same issue, only when running `PanACoTA all` and I believe it's because the `tol` option is incorrectly asking for an integer input.

When my panacota_config.ini has the following:
```
[corepers]                                                                                                                                 
tol = 0.80
```
and I run `PanACoTA all`, I get this message in my output and the pipeline will not run at all:  `ERROR: tol must be an int. Wrong value: 0.80.`

If I replace 0.80 in panacota_config.ini with the integer 80 (intending a 80% threshold) it passes the data type check and proceeds to run the pipeline; naturally, it is interpreted by the corepers module as 8000%, which will yield an empty core genome:  
```
Will generate a Persistent genome with member(s) in at least 8000% of all genomes in each family.                                                                                                                                      To be considered as persistent, a family must contain exactly 1 member in at least 8000% of all genomes. The other genomes are absent from the family.
...
The persistent genome contains 0 families, each one having exactly 1 member from at least 8000% of the 110 different genomes (that is 8800 genomes). The other genomes are absent from the family.
```
Manually running `PanACoTA corepers -t 0.80` on the same pangenome list generated by `PanACoTA all` above provides the desired output: 

```
Will generate a Persistent genome with member(s) in at least 80.0% of all genomes in each family.                                                                                                                                      To be considered as persistent, a family must contain exactly 1 member in at least 80.0% of all genomes. The other genomes are absent from the family.
...
The persistent genome contains 3774 families, each one having exactly 1 member from at least 80.0% of the 110 different genomes (that is 88 genomes). The other genomes are absent from the family.
```

**Comment by asetGem** [comment]
Hi! Thanks for letting me know!
I now corrected this, to allow floats in "tol" values.
I pushed it on master (version 1.3.1-dev4). Can you try it? If it works, I will do release version 1.4 of PanACoTA at the beginning of next year.
