### ISSUE TITLE
PanACoTA align There is not any protein for genome X

### ISSUE THREAD

**Issue by AlperYurtseven** [gem-pasteur/PanACoTA#44]
Hello, 

While running PanACoTA pipeline with Ecoli data I am getting this error messages for 36 genomes out of ~1800:

`There is not any protein for genome ESCO.1223.00001 in any family! The program will close, please fix this problem to be able to run the alignments`
`There is not any protein for genome ESCO.1223.00007 in any family! The program will close, please fix this problem to be able to run the alignments`
...

The pipeline I am following:
PanACoTA annotate
PanACoTA pangenome
PanACoTA corepers
PanACoTA align

None of them before align command had error messages. 
I have tried -X and -M option as well as lower -t values in corepers part. None of them solved the errors. 

Moreover when I manually check Proteins in annotate out folder, I can see there are proteins for all of them.

What can be the reason here? 

Thanks!

**Comment by asetGem** [comment]
Hello !

Could you share your persistent genome file so that I can check what happens there?

**Comment by AlperYurtseven** [comment]
Hi @asetGem!
 
Thank you for your reply.
Since the file size is around ~180 MB I think I cannot upload it here, may I send you via drive/email ?

**Comment by asetGem** [comment]
Yes sure. You can send it to the email linked to my profile.

**Comment by asetGem** [comment]
I had a look at your persistent file, and it appears that you don't have any gene from genome ESCO.1223.00001 (same for ESCO.1223.00007) inside! So that is why, in the alignment part, when it tries to extract persistent proteins from this genome, it says that it does not find any (does not mean that there are no proteins at all in the genome, but that there are no persistent proteins).

This could happen if these genomes have problems in the sequence, like assembly problems, duplicated parts, missing parts... Do you have any idea on how they were sequenced/assembled compared to the others? Maybe check the genome sizes, number of contigs...

For a quick fix, if you need your alignments and can ignore these 36 genomes, you can generate a persistent genome excluding these genomes, and then run the alignment step on the latter. To do so, run the corepers module with option `-l lstinfo` where lstinfo is a file with 1 line per genome name. So for you, somethiing like : 

```
ESCO.1223.01874
ESCO.1223.01875
ESCO.1223.01876
ESCO.1223.00055
...
```
(remove the 36 genomes you have in error file).

**Comment by AlperYurtseven** [comment]
Thank you for your quick reply.

For now I will continue with ignoring these 36 genomes.
I will check them more deeply.
