### ISSUE TITLE
Download individual assemblies with prepare

### ISSUE THREAD

**Issue by IsabelFE** [gem-pasteur/PanACoTA#7]
It would be useful to be able to download a specific assembly, instead of all assemblies from a given taxa (or like in my example get an assembly that belongs to a strain with no species level taxonomical assignment).

For example if I want to get this assembly: https://www.ncbi.nlm.nih.gov/assembly/GCF_000477955.1/
I could run:
`PanACoTA prepare -s "Corynebacterium sp. KPL1989"`
`PanACoTA prepare -t 69201`

Being 69201 the UID for that specific assembly

Ideally you would be able to provide a list of UIDs in a .txt file

**Comment by asetGem** [comment]
In fact, it is already the case. The problem is that the NCBI species and/or NCBI species taxid is sometimes quite difficult to find. 
Here is a browser to help you find it: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi
If I type, for example, `Corynebacterium`, I get a page with all genomes for this genus. Among them, I can find "Corynebacterium sp. KPL1989" and, when I open the link (https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1203622&lvl=3&lin=f&keep=1&srchmode=1&unlock), I can see `Taxonomy ID: 1203622`. Hence, I can get this strain by using `PanACoTA prepare -t 1203622`.

**Comment by IsabelFE** [comment]
Wow thanks! I tried to find that but I wasn't able. I tried using the following IDs marked in red in the picture. But those are really assembly IDs, rather than taxonomic IDs.
![Screen Shot 2020-10-20 at 13 15 19](https://user-images.githubusercontent.com/7309296/96621275-70d15380-12d6-11eb-9f44-3c36e90c3aea.png)

**Comment by IsabelFE** [comment]
Yeah, NCBI is sometimes a bit confusing. 
Thanks again for your work and for addressing all my issues so promptly.
