### ISSUE TITLE
IQtree error: -quiet  does not exist

### ISSUE THREAD

**Issue by IsabelFE** [gem-pasteur/PanACoTA#8]
I got this error when using the new version of IQ-Tree (COVID-19 release 2.1.1, August 20, 2020). It is running OK with the Stable release 1.6.12 (August 15, 2019), but I wanted to let you know in case someone else has this issue using the new version.

> [2020-10-20 13:07:43] : INFO  PanACoTA version 1.0.1.0
>  [2020-10-20 13:07:43] : INFO  Command used
>  PanACoTA tree -a Pangenome/Alignment_Corynes_2020_1019/Phylo-Corynes_2020_1019/Corynes_2020_1019.grp.aln -o Pangenome/Tree_Corynes_2020_1019/
> [2020-10-20 13:07:43] : INFO  Running IQtree...
> [2020-10-20 13:07:43] : INFO  IQtree command: iqtree -s Pangenome/Alignment_Corynes_2020_1019/Phylo-Corynes_2020_1019/Corynes_2020_1019.grp.aln -nt 1 -m GTR    -st DNA -pre Pangenome/Tree_Corynes_2020_1019/Corynes_2020_1019.grp.aln.iqtree_tree -quiet 
> [2020-10-20 13:07:43] : ERROR  error: iqtree -s Pangenome/Alignment_Corynes_2020_1019/Phylo-Corynes_2020_1019/Corynes_2020_1019.grp.aln -nt 1 -m GTR    -st DNA -pre Pangenome/Tree_Corynes_2020_1019/Corynes_2020_1019.grp.aln.iqtree_tree -quiet  does not exist

**Comment by asetGem** [comment]
IQtree versions 1.x and IQtree versions 2.x have a different syntax for their parameters.
The default was set to IQtree (version 1.x).
If 'iqtree' command was not found, then it looked for iqtree2 command, and, with it, used IQtree version 2.x
In your case, you did not specify a soft (so, it assumed it was iqtree 1.x), but your 'iqtree' command refered to iqtree version 2.x. So, it did not recognize IQtree 1.x arguments (like your `-quiet does not exist`, because in IQtree 2.x it is `--quiet`).

From now on (from panacota v1.1.0), **default is IQtree 2.x**
If you want to run it, just let default parameters, whatever the command used (iqtree or iqtree2).
If you want to use IQtree 1.x, add option `-s iqtree`

**Comment by IsabelFE** [comment]
Thanks! I will try using IQtree 2 next time
