### ISSUE TITLE
prokka installed with PanACoTA under conda environment did not work for me.

### ISSUE THREAD

**Issue by Happyalisa** [gem-pasteur/PanACoTA#9]
#I installed panacota under conda:
conda create -n panacota
conda activate panacota
conda install -c bioconda panacota
#then I run the following
prokka --version
#I got the following error message
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: ******/miniconda3/envs/panacota/bin/../perl5 ******/miniconda3/envs/panacota/lib/site_perl/5.26.2/x86_64-linux-thread-multi
******/miniconda3/envs/panacota/lib/site_perl/5.26.2
******/miniconda3/envs/panacota/lib/5.26.2/x86_64-linux-thread-multi ******/miniconda3/envs/panacota/lib/5.26.2 .) at ******/miniconda3/envs/panacota/bin/prokka line 32.
BEGIN failed--compilation aborted at ******/miniconda3/envs/panacota/bin/prokka line 32.

Thank you!

**Comment by asetGem** [comment]
Hi,
This seems to be a problem with bioconda installing prokka. Can you try to install prokka in your environment (`conda install prokka`) to see if this works?

**Comment by jeanrjc** [comment]
I had the same error, and I did (as recommended in the issue 519 mentioned by @asetGem) : 

`conda env config vars set PERL5LIB=$CONDA_PREFIX/lib/perl5/site_perl/5.22.0/ -n <env_name>`

It worked, but then I had an error with prokka not wanting to run because I had blast 2.10 and prokka expects at least blast 2.2. After trying to update blast (and still having the same error), I figured out that 2.10 is more recent than 2.2...
It is a [bug in prokka](https://github.com/tseemann/prokka/issues/449) which is solved in the last version of prokka, so at the end of the day I `conda upgrade prokka`, and it worked. 
I'm not sure that the first error would have occurred with the correct version of prokka. 

Is there a reason to [make the installation of prokka](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/panacota/meta.yaml#L36) with : `prokka >=1.11, <=1.14.5` and not with `prokka==1.14.5` ?

**Comment by asetGem** [comment]
Prokka output file format changed between the last versions. We know that PanACoTA can adapt to all versions between 1.11 and 1.14.5. So, we wanted to give the possibility to use a wider range of prokka versions. If the user already has a version 1.11, it is not necessary to install the new one. So, this was a choice in order to avoid useless re-installations. 
But if this leads to other problems, we can of course fix prokka version. Do you think we should do this?

**Comment by jeanrjc** [comment]
I see. Maybe you can enforce the 1.14.5 for conda installations, as it will probably be installed in a virtual env ?
Besides, `conda install panacota` installs blast 2.10.1 and prokka 1.13 (not sure why) so I think that it will fail anyway.
Also, I checked that just upgrading prokka (with `conda install prokka==1.14.5`) resolves the issue above, without the PERL5LIB thing.

**Comment by asetGem** [comment]
I now released version 1.2.0, where I fixed prokka version to 1.14.5 in the conda installation.
